# -*- coding: utf-8 -*-
"""food delivery

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wscHhg2VZ1ITxqzs6MJ7htJ4E4FouBG3

**Step 1: Reading the Uploaded**
"""

# استيراد المكتبات
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import folium

# قراءة البيانات
df = pd.read_csv("FoodDelivery_Saudi_2022-2025.csv")

"""**Step 2: Exploring the Dataset**"""

print("Shape of data:", df.shape)

#عرض لاسماء الاعمده
print(df.columns)

print("\n أول 5 صفوف من البيانات")
print(df.head())

print("# عرض معلومات عن الأعمدة وأنواع البيانات")
print(df.info())

# التحقق من القيم المفقودة
df.isnull().sum()

print("\n إحصاءات وصفية للأعمدة العددية")
print(df.describe())

# حساب القيم الفريدة في كل عمود
df.nunique()

# التحقق من الصفوف المكررة
df.duplicated().sum()

# إعداد العرض للرسوم البيانية
sns.set(style="whitegrid")
plt.rcParams['figure.figsize'] = (10,4)

# الأعمدة العددية
numeric_cols = ['Total Bill (in Saudi Riyals)', 'Delivery Duration (in minutes)', 'Customer Rating (from 1 to 5 stars)']
# رسم بياني ل Boxplot for outlier
for col in numeric_cols:
    plt.figure()
    sns.boxplot(x=df[col])
    plt.title(f'Boxplot of {col}')
    plt.show()

# اكتشاف Outliers باستخدام IQR
for col in numeric_cols:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR

    outliers = df[(df[col] < lower_bound) | (df[col] > upper_bound)]

    print(f"\nOutliers in '{col}':")
    if outliers.empty:
        print("No outliers detected.")
    else:
        print(outliers[['Order Number', col]])

"""**our data have no missing data or outliners or duplicate rows.**"""

# توزيع تقييم العملاء
sns.countplot(x="Customer Rating (from 1 to 5 stars)", data=df, palette="viridis")
plt.title("Customer Rating Distribution")
plt.show()

# توزيع مدة التوصيل
sns.histplot(df["Delivery Duration (in minutes)"], bins=15, kde=True)
plt.title("Delivery Duration Distribution")
plt.show()

# توزيع الفواتير
sns.histplot(df["Total Bill (in Saudi Riyals)"], bins=20, kde=True)
plt.title("Total Bill Distribution")
plt.show()

#   معرفة أكثر نوع مطعم عليه طلبات
orders_by_type = df['Restaurant Type'].value_counts()
plt.figure(figsize=(7,7))
plt.pie(orders_by_type.values, labels=orders_by_type.index, autopct='%1.1f%%', startangle=140)
plt.title("Restaurant Type Orders")
plt.show()

# متوسط التقييم لكل مدينة
city_rating = df.groupby("Order_City")["Customer Rating (from 1 to 5 stars)"].mean().sort_values()
city_rating.plot(kind="bar", figsize=(8,4))
plt.title("Average Rating per City")
plt.show()

# العلاقة بين مدة التوصيل والتقييم
sns.boxplot(
    x="Customer Rating (from 1 to 5 stars)",
    y="Delivery Duration (in minutes)",
    data=df
)
plt.title("Delivery Time vs Rating")
plt.show()

# Top 5 مدن حسب عدد الطلبات
top_cities = df["Order_City"].value_counts().head(5)
print("\n Top 5 Cities by Orders:\n", top_cities)

# Top 5 أنواع مطاعم حسب متوسط الفاتورة
top_restaurants = df.groupby("Restaurant Type")["Total Bill (in Saudi Riyals)"].mean().sort_values(ascending=False).head(5)
print("\n Top 5 Restaurant Types by Avg Bill:\n", top_restaurants)

# Top 5 (مدينة + نوع مطعم) حسب التقييم
city_rest_rating = df.groupby(["Order_City", "Restaurant Type"])["Customer Rating (from 1 to 5 stars)"].mean().sort_values(ascending=False).head(5)
print("\n Top 5 (City + Restaurant Type) by Avg Rating:\n", city_rest_rating)

# أنواع المطاعم
plt.figure()
sns.countplot(data=df, y='Restaurant Type', order=df['Restaurant Type'].value_counts().index)
plt.title('Number of Orders by Restaurant Type')
plt.show()

"""**Step 3: Data Cleaning & Preprocessing**"""

# دالة التصنيف

def classify_food(x):
    if x in ["Burger", "Fast Food", "Barbecue"]:
        return "American"
    elif x in ["Italian Cuisine", "Pizzeria"]:
        return "Italian"
    elif x in ["Indian Cuisine", "Sushi"]:
        return "Asian"
    elif x in ["Bakeries", "Sweets"]:
        return "Desserts & Bakery"
    elif x in ["Coffee", "Seafood", "Vegetarian/Vegan"]:
        return x  # يترك الاسم كما هو
    else:
        return x  # أي اسم آخر يبقى كما هو

#تطبيق وحفظ  التصنيف على العامود
df["Restaurant Type"] = df["Restaurant Type"].apply(classify_food)

from google.colab import files

# نحفظ الملف النهائي بصيغة Excel بدون أي تغييرات إضافية
df.to_excel("file_final.xlsx", index=False)

# تنزيل الملف على الجهاز
files.download("file_final.xlsx")

import pandas as pd

# قراءة الملف
df = pd.read_excel("/content/file_final 12.xlsx", dtype={'Time': str})


# تحويل Date إلى datetime
df['Date'] = pd.to_datetime(df['Date'], errors='coerce')

# إنشاء عمود Day من Date
df['Day'] = df['Date'].dt.day_name()

# -------- التعامل مع Time --------
# تنظيف العمود Time من أي فراغات
df['Time'] = df['Time'].str.strip()

# استخراج الساعة فقط من Time
df['Hour'] = df['Time'].str.split(':').str[0]

# -------- ترتيب الأعمدة --------
cols = df.columns.tolist()

# نخلي Day بعد Date
if 'Date' in cols and 'Day' in cols:
    date_index = cols.index('Date')
    cols.insert(date_index + 1, cols.pop(cols.index('Day')))

# نخلي Hour بعد Time
if 'Time' in cols and 'Hour' in cols:
    time_index = cols.index('Time')
    cols.insert(time_index + 1, cols.pop(cols.index('Hour')))

df = df[cols]

# اختبار أول 5 صفوف
print(df.head())

# حفظ الناتج بملف جديد
df.to_excel("final_output.xlsx", index=False)